//
//  SuitMenuModuleEvent.h
//  RestApp
//
//  Created by zxh on 14-8-22.
//  Copyright (c) 2014年 杭州迪火科技有限公司. All rights reserved.
//

#ifndef RestApp_SuitMenuModuleEvent_h
#define RestApp_SuitMenuModuleEvent_h

//套菜
#define SUITMENU_KIND 1
#define SUITMENU_PRICE 2
#define SUITMENU_ACCOUNT 3
#define SUITMENU_RATIO 4
#define SUITMENU_KABAW 5
#define SUITMENU_CODE 100
#define SUITBASE_PRICE 8

#define SUITMENU_KIND_SORT_EVENT 100
#define SUITMENU_SORT_EVENT 101


#define SUITMENU_DETAIL_SORT_EVENT 102
#define SUITMENU_CHANGE_SORT_EVENT 103

//组合
#define SUITMENUDETAIL_KIND 1
#define SUITMENUDETAIL_NUM 2


//套餐组合内商品
#define SUITMENUCHANGE_SPEC 1
#define SUITMENUCHANGE_PRICE 2
#define SUITMENUCHANGE_NUM 3

#define SUITMENU_DEDTAIL_EVENT @"SUITMENU_DEDTAIL_EVENT"
#define SUITMENU_GROUP_ADD @"SUITMENU_GROUP_ADD"
#define SUITMENU_GROUP_SORT @"SUITMENU_GROUP_SORT"
#define SUITMENU_GROUP_MENU_EDIT @"SUITMENU_GROUP_MENU_EDIT"
#define SUITMENU_GROUP_MENU_DELETE @"SUITMENU_GROUP_MENU_DELETE"
#define SUITMENU_VALUATION_EVENT @"SUITMENU_VALUATION_EVENT"

#define SUIT_MENU_PRICE @"SUIT_MENU_PRICE"
#endif
